FROM ubuntu:latest

USER root

ENV AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
ENV AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

RUN apt-get update && apt-get install -y curl

CMD ["/bin/bash"]
